config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  resources :appliances do
    member do
      patch 'toggle'
    end
  end

  mount Sidekiq::Web => '/sidekiq'
  root 'appliances#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/appliance.rb
class Appliance < ApplicationRecord
	enum state: { off: false, on: true }
	after_update_commit { broadcast_update }

	def mqtt_topic
		"Home/#{self.name}"
	end

	def toggle
		self.on? ? self.off! : self.on!
	end

	def value
		self.on? ? 'off' : 'on'
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/appliances_controller.rb
class AppliancesController < ApplicationController
  def index
    @appliances = Appliance.all
  end

  def toggle
    @appliance = Appliance.find(params[:id])

    mqtt_service = MqttService.new
    mqtt_service.publish(@appliance.mqtt_topic, @appliance.value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/appliances_helper.rb
module AppliancesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appliances/_appliance.html.erb
<% state =  appliance.on? %>
<% button_bg =  state ? "btn btn-danger" : "btn btn-primary" %>
<td><%= appliance.name %></td>
<td class="w-25 p-3"> <%= appliance.state.camelize %></td>
<td>
	<%= button_to appliance.value.camelize, toggle_appliance_path(appliance), method: :patch, remote: true, class: button_bg %>
	<% if false %>
    <%= link_to 'Show', appliance %>
    <%= link_to 'Edit', edit_appliance_path(appliance) %>
    <%= link_to 'Destroy', appliance, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</td>

app/views/appliances/index.html.erb
<h1 class="text-center mt-4">Appliances</h1>

<div class="table-responsive mx-5">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>State</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @appliances.each do |appliance| %>
        <%= turbo_stream_from appliance %>
        <tr id="<%= dom_id(appliance)%>">
          <%= render partial: 'appliance', locals: { appliance: appliance } %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <% if false %>
  <%= link_to 'New Appliance', new_appliance_path, class: 'btn btn-primary' %>
  <% end %>
</div>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Switch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>